projects:
  ampperm2:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: 3z7vc4ztvze3ndtr5qqstaj5ne
      endpoints:
        prod: >-
          https://shcwqu53wvagzasl54bk227r5m.appsync-api.us-east-1.amazonaws.com/graphql
