projects:
  ampperm1:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: kbq63pavdvf7lpog4gmyrngo3u
      endpoints:
        prod: >-
          https://eo5mqvdrxzeftketg7v6qv3jha.appsync-api.us-east-1.amazonaws.com/graphql
