projects:
  ampperm3:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: kfnysbtebjak7jbgbmaoe2dcyq
      endpoints:
        prod: >-
          https://h753opap6rhbnpya6hwck7ddme.appsync-api.us-east-1.amazonaws.com/graphql
