projects:
  ooleradminaprilfourteen:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: wsi3wbamtng4pj6oqzjjwiiwiy
      endpoints:
        prod: >-
          https://k56rm4gvgncnzll676zjeywiiu.appsync-api.us-east-1.amazonaws.com/graphql
