projects:
  ooler421:
    schemaPath: graphql/schema.json
    includes:
      - graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: swift
        generatedFileName: API.swift
        docsFilePath: graphql
        graphQLApiId: agot5ehk35g3jeobu7qmq6ykym
      endpoints:
        prod: >-
          https://unzwhbujtvgz5hnkbpu7i2i544.appsync-api.us-east-1.amazonaws.com/graphql
